apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 247882886219.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 247882886219.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 68a56b70
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
